### PR TITLE
feat(android): update library

### PR DESCRIPTION
**Pull request by m1ga**
### What do these changes do?
Update Android libraries to 16.3.3

### Why are these changes necessary?
to be compatible with Android 12

### How did you verify these changes?
I didn't. It's just a friendly reminder to update the module :smile: You can test it and merge it or create a own PR. For people who use it and want to update their apps to Titanium 10.1.1 they can test this version!

#### Verification Screenshots:
-

### Anything else a reviewer should know?
Untested, compiles fine, still uses some deprecated functions.

Test version: [ti.airship-android-9.0.0.zip](https://github.com/urbanairship/titanium-module/files/8427430/ti.airship-android-9.0.0.zip)

### CODE REVIEW

**Comment by rlepinski** [comment]
Thanks for the PR. Ill add it to our backlog to get this updated to latest SDKs with feature parity of our other plugins. Hopefully you can expect an update in the next few weeks.

**Comment by m1ga** [comment]
:+1: thanks @rlepinski

**Comment by rlepinski** [comment]
@m1ga This is still in the works. Trying to catch up on all the Ti changes that have happened since the last update.

**Comment by rlepinski** [comment]
Just released 9.0, it has a lot of breaking changes so please take a look at the migration guide - https://github.com/urbanairship/titanium-module/blob/main/documentation/migration-guide-8-9.md

**Pull request closed without merging**
